// <auto-generated />
using System;
using Corretora.C03.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Corretora.Migrations
{
    [DbContext(typeof(CorretoraDbContext))]
    [Migration("20260506212427_AddClienteCredencial")]
    partial class AddClienteCredencial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Corretora.C01.Domain.tb01_permissaoModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataAtualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataCriacao");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("descricao");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean")
                        .HasColumnName("Estado");

                    b.HasKey("id");

                    b.ToTable("Permissao");

                    b.HasData(
                        new
                        {
                            id = 1,
                            DataCriacao = new DateTime(2026, 4, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Cadastrar Funcionário",
                            Estado = true
                        },
                        new
                        {
                            id = 2,
                            DataCriacao = new DateTime(2026, 4, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Editar Funcionário",
                            Estado = true
                        },
                        new
                        {
                            id = 3,
                            DataCriacao = new DateTime(2026, 4, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Desativar Funcionário",
                            Estado = true
                        },
                        new
                        {
                            id = 4,
                            DataCriacao = new DateTime(2026, 4, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Listar Funcionários",
                            Estado = true
                        },
                        new
                        {
                            id = 5,
                            DataCriacao = new DateTime(2026, 4, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Cadastrar Cliente",
                            Estado = true
                        },
                        new
                        {
                            id = 6,
                            DataCriacao = new DateTime(2026, 4, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Editar Cliente",
                            Estado = true
                        },
                        new
                        {
                            id = 7,
                            DataCriacao = new DateTime(2026, 4, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Listar Clientes",
                            Estado = true
                        },
                        new
                        {
                            id = 8,
                            DataCriacao = new DateTime(2026, 4, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Cadastrar Imóvel",
                            Estado = true
                        },
                        new
                        {
                            id = 9,
                            DataCriacao = new DateTime(2026, 4, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Editar Imóvel",
                            Estado = true
                        },
                        new
                        {
                            id = 10,
                            DataCriacao = new DateTime(2026, 4, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Desativar Imóvel",
                            Estado = true
                        },
                        new
                        {
                            id = 11,
                            DataCriacao = new DateTime(2026, 4, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Listar Imóveis",
                            Estado = true
                        });
                });

            modelBuilder.Entity("Corretora.C01.Domain.tb02_perfilModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataAtualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataCriacao");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("descricao");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean")
                        .HasColumnName("Estado");

                    b.HasKey("id");

                    b.ToTable("Perfil");

                    b.HasData(
                        new
                        {
                            id = 1,
                            DataCriacao = new DateTime(2026, 4, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Admin",
                            Estado = true
                        },
                        new
                        {
                            id = 2,
                            DataCriacao = new DateTime(2026, 4, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Corretor",
                            Estado = true
                        },
                        new
                        {
                            id = 3,
                            DataCriacao = new DateTime(2026, 4, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Cliente",
                            Estado = true
                        });
                });

            modelBuilder.Entity("Corretora.C01.Domain.tb03_perfiL_permissaoModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataAtualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataCriacao");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean")
                        .HasColumnName("Estado");

                    b.Property<int>("Idtb01_permissaoModel")
                        .HasColumnType("integer")
                        .HasColumnName("IdPermissao");

                    b.Property<int>("Idtb02_perfilModel")
                        .HasColumnType("integer")
                        .HasColumnName("IdPerfil");

                    b.HasKey("id");

                    b.HasIndex("Idtb01_permissaoModel");

                    b.HasIndex("Idtb02_perfilModel");

                    b.ToTable("PerfilPermissao");

                    b.HasData(
                        new
                        {
                            id = 1,
                            DataCriacao = new DateTime(2026, 4, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Estado = true,
                            Idtb01_permissaoModel = 1,
                            Idtb02_perfilModel = 1
                        },
                        new
                        {
                            id = 2,
                            DataCriacao = new DateTime(2026, 4, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Estado = true,
                            Idtb01_permissaoModel = 2,
                            Idtb02_perfilModel = 1
                        },
                        new
                        {
                            id = 3,
                            DataCriacao = new DateTime(2026, 4, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Estado = true,
                            Idtb01_permissaoModel = 3,
                            Idtb02_perfilModel = 1
                        },
                        new
                        {
                            id = 4,
                            DataCriacao = new DateTime(2026, 4, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Estado = true,
                            Idtb01_permissaoModel = 4,
                            Idtb02_perfilModel = 1
                        },
                        new
                        {
                            id = 5,
                            DataCriacao = new DateTime(2026, 4, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Estado = true,
                            Idtb01_permissaoModel = 5,
                            Idtb02_perfilModel = 1
                        },
                        new
                        {
                            id = 6,
                            DataCriacao = new DateTime(2026, 4, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Estado = true,
                            Idtb01_permissaoModel = 6,
                            Idtb02_perfilModel = 1
                        },
                        new
                        {
                            id = 7,
                            DataCriacao = new DateTime(2026, 4, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Estado = true,
                            Idtb01_permissaoModel = 7,
                            Idtb02_perfilModel = 1
                        },
                        new
                        {
                            id = 8,
                            DataCriacao = new DateTime(2026, 4, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Estado = true,
                            Idtb01_permissaoModel = 8,
                            Idtb02_perfilModel = 1
                        },
                        new
                        {
                            id = 9,
                            DataCriacao = new DateTime(2026, 4, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Estado = true,
                            Idtb01_permissaoModel = 9,
                            Idtb02_perfilModel = 1
                        },
                        new
                        {
                            id = 10,
                            DataCriacao = new DateTime(2026, 4, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Estado = true,
                            Idtb01_permissaoModel = 10,
                            Idtb02_perfilModel = 1
                        },
                        new
                        {
                            id = 11,
                            DataCriacao = new DateTime(2026, 4, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Estado = true,
                            Idtb01_permissaoModel = 11,
                            Idtb02_perfilModel = 1
                        },
                        new
                        {
                            id = 12,
                            DataCriacao = new DateTime(2026, 4, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Estado = true,
                            Idtb01_permissaoModel = 5,
                            Idtb02_perfilModel = 2
                        },
                        new
                        {
                            id = 13,
                            DataCriacao = new DateTime(2026, 4, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Estado = true,
                            Idtb01_permissaoModel = 6,
                            Idtb02_perfilModel = 2
                        },
                        new
                        {
                            id = 14,
                            DataCriacao = new DateTime(2026, 4, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Estado = true,
                            Idtb01_permissaoModel = 7,
                            Idtb02_perfilModel = 2
                        },
                        new
                        {
                            id = 15,
                            DataCriacao = new DateTime(2026, 4, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Estado = true,
                            Idtb01_permissaoModel = 8,
                            Idtb02_perfilModel = 2
                        },
                        new
                        {
                            id = 16,
                            DataCriacao = new DateTime(2026, 4, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Estado = true,
                            Idtb01_permissaoModel = 9,
                            Idtb02_perfilModel = 2
                        },
                        new
                        {
                            id = 17,
                            DataCriacao = new DateTime(2026, 4, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Estado = true,
                            Idtb01_permissaoModel = 10,
                            Idtb02_perfilModel = 2
                        },
                        new
                        {
                            id = 18,
                            DataCriacao = new DateTime(2026, 4, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Estado = true,
                            Idtb01_permissaoModel = 11,
                            Idtb02_perfilModel = 2
                        });
                });

            modelBuilder.Entity("Corretora.C01.Domain.tb04_funcionarioModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean")
                        .HasColumnName("Estado");

                    b.Property<int>("Idtb02_perfilModel")
                        .HasColumnType("integer")
                        .HasColumnName("IdPerfil");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Nome");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Numero");

                    b.Property<int?>("tb01_permissaoModelid")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Idtb02_perfilModel");

                    b.HasIndex("tb01_permissaoModelid");

                    b.ToTable("funcionario");
                });

            modelBuilder.Entity("Corretora.C01.Domain.tb05_credencial_acessoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Idtb04_funcionarioModel")
                        .HasColumnType("integer")
                        .HasColumnName("tb04_funcionarioModel");

                    b.Property<string>("Senha_hash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Senha_hash");

                    b.Property<string>("Senha_salt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Senha_salt");

                    b.Property<int?>("tb06_clienteModelId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Idtb04_funcionarioModel");

                    b.HasIndex("tb06_clienteModelId");

                    b.ToTable("Credencial");
                });

            modelBuilder.Entity("Corretora.C01.Domain.tb06_clienteModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataAtualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataCriacao");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean")
                        .HasColumnName("Estado");

                    b.Property<int>("Idtb02_perfilModel")
                        .HasColumnType("integer")
                        .HasColumnName("IdPerfil");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("Nome");

                    b.HasKey("Id");

                    b.HasIndex("Idtb02_perfilModel");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("Corretora.C01.Domain.tb07_telefoneModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Numero");

                    b.Property<int>("tb04_funcionarioModel")
                        .HasColumnType("integer")
                        .HasColumnName("tb04_funcionarioModel");

                    b.Property<int>("tb06_clienteModel")
                        .HasColumnType("integer")
                        .HasColumnName("tb06_clienteModel");

                    b.HasKey("Id");

                    b.HasIndex("tb04_funcionarioModel");

                    b.HasIndex("tb06_clienteModel");

                    b.ToTable("Telefone");
                });

            modelBuilder.Entity("Corretora.C01.Domain.tb08_emailModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Email");

                    b.Property<int>("tb04_funcionarioModel")
                        .HasColumnType("integer")
                        .HasColumnName("tb04_funcionarioMOdel");

                    b.Property<int>("tb06_clienteModel")
                        .HasColumnType("integer")
                        .HasColumnName("tb06_clienteModel");

                    b.HasKey("Id");

                    b.HasIndex("tb04_funcionarioModel");

                    b.HasIndex("tb06_clienteModel");

                    b.ToTable("Email");
                });

            modelBuilder.Entity("Corretora.C01.Domain.tb09_tipo_imovelModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Descricao");

                    b.HasKey("Id");

                    b.ToTable("TipoImovel");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Apartamento"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Casa"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Terreno"
                        });
                });

            modelBuilder.Entity("Corretora.C01.Domain.tb10_tipologiaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Descricao");

                    b.HasKey("Id");

                    b.ToTable("Tipologia");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "T1"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "T2"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "T3"
                        });
                });

            modelBuilder.Entity("Corretora.C01.Domain.tb11_imovelModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Descricao");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean")
                        .HasColumnName("Estado");

                    b.Property<decimal>("Preco")
                        .HasColumnType("numeric")
                        .HasColumnName("Preco");

                    b.Property<int>("tb04_funcionarioModel")
                        .HasColumnType("integer")
                        .HasColumnName("tb04_funcionarioModel");

                    b.Property<int>("tb09_tipo_imovelModel")
                        .HasColumnType("integer")
                        .HasColumnName("tb09_tipo_imovelModel");

                    b.Property<int>("tb10_tipologiaModel")
                        .HasColumnType("integer")
                        .HasColumnName("tb010_tipologiaModel");

                    b.Property<int>("tb18_proprietarioModel")
                        .HasColumnType("integer")
                        .HasColumnName("tb18_proprietarioModel");

                    b.HasKey("Id");

                    b.HasIndex("tb04_funcionarioModel");

                    b.HasIndex("tb09_tipo_imovelModel");

                    b.HasIndex("tb10_tipologiaModel");

                    b.HasIndex("tb18_proprietarioModel");

                    b.ToTable("Imovel");
                });

            modelBuilder.Entity("Corretora.C01.Domain.tb12_fotoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Foto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Foto");

                    b.Property<int>("tb09_tipo_imovel")
                        .HasColumnType("integer")
                        .HasColumnName("TipoImovel");

                    b.Property<int>("tb11_imovelModel")
                        .HasColumnType("integer")
                        .HasColumnName("tb11_imovelModel");

                    b.HasKey("Id");

                    b.HasIndex("tb11_imovelModel");

                    b.ToTable("Foto");
                });

            modelBuilder.Entity("Corretora.C01.Domain.tb13_videoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Video")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Video");

                    b.Property<int>("tb09_tipo_imovel")
                        .HasColumnType("integer")
                        .HasColumnName("TipoImovel");

                    b.Property<int>("tb11_imovelModel")
                        .HasColumnType("integer")
                        .HasColumnName("tb11_imovelModel");

                    b.HasKey("Id");

                    b.HasIndex("tb11_imovelModel");

                    b.ToTable("Video");
                });

            modelBuilder.Entity("Corretora.C01.Domain.tb14_provinciaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Nome");

                    b.HasKey("Id");

                    b.ToTable("Provincia");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Luanda"
                        });
                });

            modelBuilder.Entity("Corretora.C01.Domain.tb15_municipioModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Nome");

                    b.Property<int>("tb14_provinciaModel")
                        .HasColumnType("integer")
                        .HasColumnName("Provincia");

                    b.HasKey("Id");

                    b.HasIndex("tb14_provinciaModel");

                    b.ToTable("Municipio");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Luanda",
                            tb14_provinciaModel = 1
                        });
                });

            modelBuilder.Entity("Corretora.C01.Domain.tb16_bairroModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Nome");

                    b.Property<int>("tb15_municipioModel")
                        .HasColumnType("integer")
                        .HasColumnName("Municipio");

                    b.HasKey("Id");

                    b.HasIndex("tb15_municipioModel");

                    b.ToTable("Bairro");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Centro",
                            tb15_municipioModel = 1
                        });
                });

            modelBuilder.Entity("Corretora.C01.Domain.tb17_enderecoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Nome");

                    b.Property<int>("tb09_tipo_imovelModel")
                        .HasColumnType("integer")
                        .HasColumnName("TipoImovel");

                    b.Property<int>("tb11_imovelModel")
                        .HasColumnType("integer")
                        .HasColumnName("tb11_imovelModel");

                    b.Property<int>("tb16_bairroModel")
                        .HasColumnType("integer")
                        .HasColumnName("Bairro");

                    b.HasKey("Id");

                    b.HasIndex("tb11_imovelModel");

                    b.HasIndex("tb16_bairroModel");

                    b.ToTable("Endereco");
                });

            modelBuilder.Entity("Corretora.C01.Domain.tb18_proprietarioModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Nome");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("tb09_tipo_imovelModel")
                        .HasColumnType("integer")
                        .HasColumnName("TipoImovel");

                    b.Property<int?>("tb11_imovelModelId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("tb11_imovelModelId");

                    b.ToTable("Proprietario");
                });

            modelBuilder.Entity("Corretora.C01.Domain.tb19_estado_solicitacaoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Nome");

                    b.HasKey("Id");

                    b.ToTable("EstadoSolicitacao");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Solicitação pendente",
                            Nome = "Pendente"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Solicitação aprovada",
                            Nome = "Aprovada"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Solicitação rejeitada",
                            Nome = "Rejeitada"
                        });
                });

            modelBuilder.Entity("Corretora.C01.Domain.tb20_solicitacaoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Data");

                    b.Property<int>("tb06_clienteModel")
                        .HasColumnType("integer")
                        .HasColumnName("Cliente");

                    b.Property<int>("tb11_imovelModel")
                        .HasColumnType("integer")
                        .HasColumnName("Imovel");

                    b.Property<int>("tb19_estado_solicitacaoModel")
                        .HasColumnType("integer")
                        .HasColumnName("EstadoSolicitacao");

                    b.HasKey("Id");

                    b.HasIndex("tb06_clienteModel");

                    b.HasIndex("tb11_imovelModel");

                    b.HasIndex("tb19_estado_solicitacaoModel");

                    b.ToTable("Solicitacao");
                });

            modelBuilder.Entity("Corretora.C01.Domain.tb21_favoritoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("tb06_clienteModel")
                        .HasColumnType("integer")
                        .HasColumnName("Cliente");

                    b.Property<int>("tb11_imovelModel")
                        .HasColumnType("integer")
                        .HasColumnName("Imovel");

                    b.HasKey("Id");

                    b.HasIndex("tb06_clienteModel");

                    b.HasIndex("tb11_imovelModel");

                    b.ToTable("Favorito");
                });

            modelBuilder.Entity("Corretora.C01.Domain.tb03_perfiL_permissaoModel", b =>
                {
                    b.HasOne("Corretora.C01.Domain.tb01_permissaoModel", "Permissao")
                        .WithMany("PerfilPermissao")
                        .HasForeignKey("Idtb01_permissaoModel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PerfilPermissao_Permissao");

                    b.HasOne("Corretora.C01.Domain.tb02_perfilModel", "Perfil")
                        .WithMany("PerfilPermissao")
                        .HasForeignKey("Idtb02_perfilModel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PerfilPermissao_Perfil");

                    b.Navigation("Perfil");

                    b.Navigation("Permissao");
                });

            modelBuilder.Entity("Corretora.C01.Domain.tb04_funcionarioModel", b =>
                {
                    b.HasOne("Corretora.C01.Domain.tb02_perfilModel", "Perfil")
                        .WithMany("Funcionarios")
                        .HasForeignKey("Idtb02_perfilModel")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Funcionario_Perfil");

                    b.HasOne("Corretora.C01.Domain.tb01_permissaoModel", null)
                        .WithMany("Funcionario")
                        .HasForeignKey("tb01_permissaoModelid");

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("Corretora.C01.Domain.tb05_credencial_acessoModel", b =>
                {
                    b.HasOne("Corretora.C01.Domain.tb04_funcionarioModel", "Funcionario")
                        .WithMany("Credencial")
                        .HasForeignKey("Idtb04_funcionarioModel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Corretora.C01.Domain.tb06_clienteModel", null)
                        .WithMany("Credencial")
                        .HasForeignKey("tb06_clienteModelId");

                    b.Navigation("Funcionario");
                });

            modelBuilder.Entity("Corretora.C01.Domain.tb06_clienteModel", b =>
                {
                    b.HasOne("Corretora.C01.Domain.tb02_perfilModel", "Perfil")
                        .WithMany("Clientes")
                        .HasForeignKey("Idtb02_perfilModel")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Cliente_Perfil");

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("Corretora.C01.Domain.tb07_telefoneModel", b =>
                {
                    b.HasOne("Corretora.C01.Domain.tb04_funcionarioModel", "Funcionario")
                        .WithMany("Telefone")
                        .HasForeignKey("tb04_funcionarioModel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Corretora.C01.Domain.tb06_clienteModel", "Cliente")
                        .WithMany("Telefone")
                        .HasForeignKey("tb06_clienteModel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Funcionario");
                });

            modelBuilder.Entity("Corretora.C01.Domain.tb08_emailModel", b =>
                {
                    b.HasOne("Corretora.C01.Domain.tb04_funcionarioModel", "Funcionario")
                        .WithMany("Email")
                        .HasForeignKey("tb04_funcionarioModel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Corretora.C01.Domain.tb06_clienteModel", "Cliente")
                        .WithMany("Email")
                        .HasForeignKey("tb06_clienteModel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Funcionario");
                });

            modelBuilder.Entity("Corretora.C01.Domain.tb11_imovelModel", b =>
                {
                    b.HasOne("Corretora.C01.Domain.tb04_funcionarioModel", "Funcionario")
                        .WithMany("Imovel")
                        .HasForeignKey("tb04_funcionarioModel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Corretora.C01.Domain.tb09_tipo_imovelModel", "TipoImovel")
                        .WithMany("Imovel")
                        .HasForeignKey("tb09_tipo_imovelModel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Corretora.C01.Domain.tb10_tipologiaModel", "Tipologia")
                        .WithMany("Imovel")
                        .HasForeignKey("tb10_tipologiaModel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Corretora.C01.Domain.tb18_proprietarioModel", "ProprietarioModel")
                        .WithMany("Imoveis")
                        .HasForeignKey("tb18_proprietarioModel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcionario");

                    b.Navigation("ProprietarioModel");

                    b.Navigation("TipoImovel");

                    b.Navigation("Tipologia");
                });

            modelBuilder.Entity("Corretora.C01.Domain.tb12_fotoModel", b =>
                {
                    b.HasOne("Corretora.C01.Domain.tb11_imovelModel", "Imovel")
                        .WithMany("Foto")
                        .HasForeignKey("tb11_imovelModel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Imovel");
                });

            modelBuilder.Entity("Corretora.C01.Domain.tb13_videoModel", b =>
                {
                    b.HasOne("Corretora.C01.Domain.tb11_imovelModel", "Imovel")
                        .WithMany("Video")
                        .HasForeignKey("tb11_imovelModel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Imovel");
                });

            modelBuilder.Entity("Corretora.C01.Domain.tb15_municipioModel", b =>
                {
                    b.HasOne("Corretora.C01.Domain.tb14_provinciaModel", "Provincia")
                        .WithMany("Municipio")
                        .HasForeignKey("tb14_provinciaModel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provincia");
                });

            modelBuilder.Entity("Corretora.C01.Domain.tb16_bairroModel", b =>
                {
                    b.HasOne("Corretora.C01.Domain.tb15_municipioModel", "Municipio")
                        .WithMany("Bairro")
                        .HasForeignKey("tb15_municipioModel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Municipio");
                });

            modelBuilder.Entity("Corretora.C01.Domain.tb17_enderecoModel", b =>
                {
                    b.HasOne("Corretora.C01.Domain.tb11_imovelModel", "Imovel")
                        .WithMany("Endereco")
                        .HasForeignKey("tb11_imovelModel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Corretora.C01.Domain.tb16_bairroModel", "Bairro")
                        .WithMany("Endereco")
                        .HasForeignKey("tb16_bairroModel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bairro");

                    b.Navigation("Imovel");
                });

            modelBuilder.Entity("Corretora.C01.Domain.tb18_proprietarioModel", b =>
                {
                    b.HasOne("Corretora.C01.Domain.tb11_imovelModel", null)
                        .WithMany("Proprietario")
                        .HasForeignKey("tb11_imovelModelId");
                });

            modelBuilder.Entity("Corretora.C01.Domain.tb20_solicitacaoModel", b =>
                {
                    b.HasOne("Corretora.C01.Domain.tb06_clienteModel", "Cliente")
                        .WithMany("Solicitacoes")
                        .HasForeignKey("tb06_clienteModel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Corretora.C01.Domain.tb11_imovelModel", "Imovel")
                        .WithMany("Solicitacao")
                        .HasForeignKey("tb11_imovelModel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Corretora.C01.Domain.tb19_estado_solicitacaoModel", "EstadoSolicitacao")
                        .WithMany("Solicitacao")
                        .HasForeignKey("tb19_estado_solicitacaoModel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("EstadoSolicitacao");

                    b.Navigation("Imovel");
                });

            modelBuilder.Entity("Corretora.C01.Domain.tb21_favoritoModel", b =>
                {
                    b.HasOne("Corretora.C01.Domain.tb06_clienteModel", "Cliente")
                        .WithMany("Favoritos")
                        .HasForeignKey("tb06_clienteModel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Corretora.C01.Domain.tb11_imovelModel", "Imovel")
                        .WithMany("Favorito")
                        .HasForeignKey("tb11_imovelModel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Imovel");
                });

            modelBuilder.Entity("Corretora.C01.Domain.tb01_permissaoModel", b =>
                {
                    b.Navigation("Funcionario");

                    b.Navigation("PerfilPermissao");
                });

            modelBuilder.Entity("Corretora.C01.Domain.tb02_perfilModel", b =>
                {
                    b.Navigation("Clientes");

                    b.Navigation("Funcionarios");

                    b.Navigation("PerfilPermissao");
                });

            modelBuilder.Entity("Corretora.C01.Domain.tb04_funcionarioModel", b =>
                {
                    b.Navigation("Credencial");

                    b.Navigation("Email");

                    b.Navigation("Imovel");

                    b.Navigation("Telefone");
                });

            modelBuilder.Entity("Corretora.C01.Domain.tb06_clienteModel", b =>
                {
                    b.Navigation("Credencial");

                    b.Navigation("Email");

                    b.Navigation("Favoritos");

                    b.Navigation("Solicitacoes");

                    b.Navigation("Telefone");
                });

            modelBuilder.Entity("Corretora.C01.Domain.tb09_tipo_imovelModel", b =>
                {
                    b.Navigation("Imovel");
                });

            modelBuilder.Entity("Corretora.C01.Domain.tb10_tipologiaModel", b =>
                {
                    b.Navigation("Imovel");
                });

            modelBuilder.Entity("Corretora.C01.Domain.tb11_imovelModel", b =>
                {
                    b.Navigation("Endereco");

                    b.Navigation("Favorito");

                    b.Navigation("Foto");

                    b.Navigation("Proprietario");

                    b.Navigation("Solicitacao");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("Corretora.C01.Domain.tb14_provinciaModel", b =>
                {
                    b.Navigation("Municipio");
                });

            modelBuilder.Entity("Corretora.C01.Domain.tb15_municipioModel", b =>
                {
                    b.Navigation("Bairro");
                });

            modelBuilder.Entity("Corretora.C01.Domain.tb16_bairroModel", b =>
                {
                    b.Navigation("Endereco");
                });

            modelBuilder.Entity("Corretora.C01.Domain.tb18_proprietarioModel", b =>
                {
                    b.Navigation("Imoveis");
                });

            modelBuilder.Entity("Corretora.C01.Domain.tb19_estado_solicitacaoModel", b =>
                {
                    b.Navigation("Solicitacao");
                });
#pragma warning restore 612, 618
        }
    }
}
