/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginFuncionariosRouteImport } from './routes/login-funcionarios'
import { Route as CorretorIndexRouteImport } from './routes/corretor.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ImoveisIdRouteImport } from './routes/imoveis.$id'
import { Route as CorretorImoveisRouteImport } from './routes/corretor.imoveis'
import { Route as AdminUtilizadoresRouteImport } from './routes/admin.utilizadores'
import { Route as AdminImoveisRouteImport } from './routes/admin.imoveis'
import { Route as AdminImoveisInativosRouteImport } from './routes/admin.imoveis.inativos'

const LoginFuncionariosRoute = LoginFuncionariosRouteImport.update({
  id: '/login-funcionarios',
  path: '/login-funcionarios',
  getParentRoute: () => rootRouteImport,
} as any)
const CorretorIndexRoute = CorretorIndexRouteImport.update({
  id: '/corretor/',
  path: '/corretor/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImoveisIdRoute = ImoveisIdRouteImport.update({
  id: '/imoveis/$id',
  path: '/imoveis/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CorretorImoveisRoute = CorretorImoveisRouteImport.update({
  id: '/corretor/imoveis',
  path: '/corretor/imoveis',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUtilizadoresRoute = AdminUtilizadoresRouteImport.update({
  id: '/admin/utilizadores',
  path: '/admin/utilizadores',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminImoveisRoute = AdminImoveisRouteImport.update({
  id: '/admin/imoveis',
  path: '/admin/imoveis',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminImoveisInativosRoute = AdminImoveisInativosRouteImport.update({
  id: '/inativos',
  path: '/inativos',
  getParentRoute: () => AdminImoveisRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login-funcionarios': typeof LoginFuncionariosRoute
  '/admin/imoveis': typeof AdminImoveisRouteWithChildren
  '/admin/utilizadores': typeof AdminUtilizadoresRoute
  '/corretor/imoveis': typeof CorretorImoveisRoute
  '/imoveis/$id': typeof ImoveisIdRoute
  '/admin/': typeof AdminIndexRoute
  '/corretor/': typeof CorretorIndexRoute
  '/admin/imoveis/inativos': typeof AdminImoveisInativosRoute
}
export interface FileRoutesByTo {
  '/login-funcionarios': typeof LoginFuncionariosRoute
  '/admin/imoveis': typeof AdminImoveisRouteWithChildren
  '/admin/utilizadores': typeof AdminUtilizadoresRoute
  '/corretor/imoveis': typeof CorretorImoveisRoute
  '/imoveis/$id': typeof ImoveisIdRoute
  '/admin': typeof AdminIndexRoute
  '/corretor': typeof CorretorIndexRoute
  '/admin/imoveis/inativos': typeof AdminImoveisInativosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/login-funcionarios': typeof LoginFuncionariosRoute
  '/admin/imoveis': typeof AdminImoveisRouteWithChildren
  '/admin/utilizadores': typeof AdminUtilizadoresRoute
  '/corretor/imoveis': typeof CorretorImoveisRoute
  '/imoveis/$id': typeof ImoveisIdRoute
  '/admin/': typeof AdminIndexRoute
  '/corretor/': typeof CorretorIndexRoute
  '/admin/imoveis/inativos': typeof AdminImoveisInativosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login-funcionarios'
    | '/admin/imoveis'
    | '/admin/utilizadores'
    | '/corretor/imoveis'
    | '/imoveis/$id'
    | '/admin/'
    | '/corretor/'
    | '/admin/imoveis/inativos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login-funcionarios'
    | '/admin/imoveis'
    | '/admin/utilizadores'
    | '/corretor/imoveis'
    | '/imoveis/$id'
    | '/admin'
    | '/corretor'
    | '/admin/imoveis/inativos'
  id:
    | '__root__'
    | '/login-funcionarios'
    | '/admin/imoveis'
    | '/admin/utilizadores'
    | '/corretor/imoveis'
    | '/imoveis/$id'
    | '/admin/'
    | '/corretor/'
    | '/admin/imoveis/inativos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LoginFuncionariosRoute: typeof LoginFuncionariosRoute
  AdminImoveisRoute: typeof AdminImoveisRouteWithChildren
  AdminUtilizadoresRoute: typeof AdminUtilizadoresRoute
  CorretorImoveisRoute: typeof CorretorImoveisRoute
  ImoveisIdRoute: typeof ImoveisIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  CorretorIndexRoute: typeof CorretorIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login-funcionarios': {
      id: '/login-funcionarios'
      path: '/login-funcionarios'
      fullPath: '/login-funcionarios'
      preLoaderRoute: typeof LoginFuncionariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corretor/': {
      id: '/corretor/'
      path: '/corretor'
      fullPath: '/corretor/'
      preLoaderRoute: typeof CorretorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imoveis/$id': {
      id: '/imoveis/$id'
      path: '/imoveis/$id'
      fullPath: '/imoveis/$id'
      preLoaderRoute: typeof ImoveisIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corretor/imoveis': {
      id: '/corretor/imoveis'
      path: '/corretor/imoveis'
      fullPath: '/corretor/imoveis'
      preLoaderRoute: typeof CorretorImoveisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/utilizadores': {
      id: '/admin/utilizadores'
      path: '/admin/utilizadores'
      fullPath: '/admin/utilizadores'
      preLoaderRoute: typeof AdminUtilizadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/imoveis': {
      id: '/admin/imoveis'
      path: '/admin/imoveis'
      fullPath: '/admin/imoveis'
      preLoaderRoute: typeof AdminImoveisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/imoveis/inativos': {
      id: '/admin/imoveis/inativos'
      path: '/inativos'
      fullPath: '/admin/imoveis/inativos'
      preLoaderRoute: typeof AdminImoveisInativosRouteImport
      parentRoute: typeof AdminImoveisRoute
    }
  }
}

interface AdminImoveisRouteChildren {
  AdminImoveisInativosRoute: typeof AdminImoveisInativosRoute
}

const AdminImoveisRouteChildren: AdminImoveisRouteChildren = {
  AdminImoveisInativosRoute: AdminImoveisInativosRoute,
}

const AdminImoveisRouteWithChildren = AdminImoveisRoute._addFileChildren(
  AdminImoveisRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  LoginFuncionariosRoute: LoginFuncionariosRoute,
  AdminImoveisRoute: AdminImoveisRouteWithChildren,
  AdminUtilizadoresRoute: AdminUtilizadoresRoute,
  CorretorImoveisRoute: CorretorImoveisRoute,
  ImoveisIdRoute: ImoveisIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  CorretorIndexRoute: CorretorIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
