/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as RegistoRouteImport } from './routes/registo'
import { Route as LoginClienteRouteImport } from './routes/login-cliente'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ImoveisIndexRouteImport } from './routes/imoveis.index'
import { Route as ClienteIndexRouteImport } from './routes/cliente.index'
import { Route as ImoveisIdRouteImport } from './routes/imoveis.$id'
import { Route as ClienteVisitasRouteImport } from './routes/cliente.visitas'
import { Route as ClienteFavoritosRouteImport } from './routes/cliente.favoritos'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistoRoute = RegistoRouteImport.update({
  id: '/registo',
  path: '/registo',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginClienteRoute = LoginClienteRouteImport.update({
  id: '/login-cliente',
  path: '/login-cliente',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImoveisIndexRoute = ImoveisIndexRouteImport.update({
  id: '/imoveis/',
  path: '/imoveis/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteIndexRoute = ClienteIndexRouteImport.update({
  id: '/cliente/',
  path: '/cliente/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImoveisIdRoute = ImoveisIdRouteImport.update({
  id: '/imoveis/$id',
  path: '/imoveis/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteVisitasRoute = ClienteVisitasRouteImport.update({
  id: '/cliente/visitas',
  path: '/cliente/visitas',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteFavoritosRoute = ClienteFavoritosRouteImport.update({
  id: '/cliente/favoritos',
  path: '/cliente/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/login': typeof LoginRoute
  '/login-cliente': typeof LoginClienteRoute
  '/registo': typeof RegistoRoute
  '/sobre': typeof SobreRoute
  '/cliente/favoritos': typeof ClienteFavoritosRoute
  '/cliente/visitas': typeof ClienteVisitasRoute
  '/imoveis/$id': typeof ImoveisIdRoute
  '/cliente/': typeof ClienteIndexRoute
  '/imoveis/': typeof ImoveisIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/login': typeof LoginRoute
  '/login-cliente': typeof LoginClienteRoute
  '/registo': typeof RegistoRoute
  '/sobre': typeof SobreRoute
  '/cliente/favoritos': typeof ClienteFavoritosRoute
  '/cliente/visitas': typeof ClienteVisitasRoute
  '/imoveis/$id': typeof ImoveisIdRoute
  '/cliente': typeof ClienteIndexRoute
  '/imoveis': typeof ImoveisIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/login': typeof LoginRoute
  '/login-cliente': typeof LoginClienteRoute
  '/registo': typeof RegistoRoute
  '/sobre': typeof SobreRoute
  '/cliente/favoritos': typeof ClienteFavoritosRoute
  '/cliente/visitas': typeof ClienteVisitasRoute
  '/imoveis/$id': typeof ImoveisIdRoute
  '/cliente/': typeof ClienteIndexRoute
  '/imoveis/': typeof ImoveisIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contacto'
    | '/login'
    | '/login-cliente'
    | '/registo'
    | '/sobre'
    | '/cliente/favoritos'
    | '/cliente/visitas'
    | '/imoveis/$id'
    | '/cliente/'
    | '/imoveis/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacto'
    | '/login'
    | '/login-cliente'
    | '/registo'
    | '/sobre'
    | '/cliente/favoritos'
    | '/cliente/visitas'
    | '/imoveis/$id'
    | '/cliente'
    | '/imoveis'
  id:
    | '__root__'
    | '/'
    | '/contacto'
    | '/login'
    | '/login-cliente'
    | '/registo'
    | '/sobre'
    | '/cliente/favoritos'
    | '/cliente/visitas'
    | '/imoveis/$id'
    | '/cliente/'
    | '/imoveis/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactoRoute: typeof ContactoRoute
  LoginRoute: typeof LoginRoute
  LoginClienteRoute: typeof LoginClienteRoute
  RegistoRoute: typeof RegistoRoute
  SobreRoute: typeof SobreRoute
  ClienteFavoritosRoute: typeof ClienteFavoritosRoute
  ClienteVisitasRoute: typeof ClienteVisitasRoute
  ImoveisIdRoute: typeof ImoveisIdRoute
  ClienteIndexRoute: typeof ClienteIndexRoute
  ImoveisIndexRoute: typeof ImoveisIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registo': {
      id: '/registo'
      path: '/registo'
      fullPath: '/registo'
      preLoaderRoute: typeof RegistoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login-cliente': {
      id: '/login-cliente'
      path: '/login-cliente'
      fullPath: '/login-cliente'
      preLoaderRoute: typeof LoginClienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imoveis/': {
      id: '/imoveis/'
      path: '/imoveis'
      fullPath: '/imoveis/'
      preLoaderRoute: typeof ImoveisIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente/': {
      id: '/cliente/'
      path: '/cliente'
      fullPath: '/cliente/'
      preLoaderRoute: typeof ClienteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imoveis/$id': {
      id: '/imoveis/$id'
      path: '/imoveis/$id'
      fullPath: '/imoveis/$id'
      preLoaderRoute: typeof ImoveisIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente/visitas': {
      id: '/cliente/visitas'
      path: '/cliente/visitas'
      fullPath: '/cliente/visitas'
      preLoaderRoute: typeof ClienteVisitasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente/favoritos': {
      id: '/cliente/favoritos'
      path: '/cliente/favoritos'
      fullPath: '/cliente/favoritos'
      preLoaderRoute: typeof ClienteFavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactoRoute: ContactoRoute,
  LoginRoute: LoginRoute,
  LoginClienteRoute: LoginClienteRoute,
  RegistoRoute: RegistoRoute,
  SobreRoute: SobreRoute,
  ClienteFavoritosRoute: ClienteFavoritosRoute,
  ClienteVisitasRoute: ClienteVisitasRoute,
  ImoveisIdRoute: ImoveisIdRoute,
  ClienteIndexRoute: ClienteIndexRoute,
  ImoveisIndexRoute: ImoveisIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
