/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as RegistoRouteImport } from './routes/registo'
import { Route as LoginFuncionariosRouteImport } from './routes/login-funcionarios'
import { Route as LoginClienteRouteImport } from './routes/login-cliente'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ImoveisIndexRouteImport } from './routes/imoveis.index'
import { Route as CorretorIndexRouteImport } from './routes/corretor.index'
import { Route as ClienteIndexRouteImport } from './routes/cliente.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ImoveisIdRouteImport } from './routes/imoveis.$id'
import { Route as CorretorImoveisRouteImport } from './routes/corretor.imoveis'
import { Route as ClienteVisitasRouteImport } from './routes/cliente.visitas'
import { Route as ClienteFavoritosRouteImport } from './routes/cliente.favoritos'
import { Route as AdminUtilizadoresRouteImport } from './routes/admin.utilizadores'
import { Route as AdminImoveisRouteImport } from './routes/admin.imoveis'
import { Route as AdminImoveisInativosRouteImport } from './routes/admin.imoveis.inativos'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistoRoute = RegistoRouteImport.update({
  id: '/registo',
  path: '/registo',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginFuncionariosRoute = LoginFuncionariosRouteImport.update({
  id: '/login-funcionarios',
  path: '/login-funcionarios',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginClienteRoute = LoginClienteRouteImport.update({
  id: '/login-cliente',
  path: '/login-cliente',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImoveisIndexRoute = ImoveisIndexRouteImport.update({
  id: '/imoveis/',
  path: '/imoveis/',
  getParentRoute: () => rootRouteImport,
} as any)
const CorretorIndexRoute = CorretorIndexRouteImport.update({
  id: '/corretor/',
  path: '/corretor/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteIndexRoute = ClienteIndexRouteImport.update({
  id: '/cliente/',
  path: '/cliente/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImoveisIdRoute = ImoveisIdRouteImport.update({
  id: '/imoveis/$id',
  path: '/imoveis/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CorretorImoveisRoute = CorretorImoveisRouteImport.update({
  id: '/corretor/imoveis',
  path: '/corretor/imoveis',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteVisitasRoute = ClienteVisitasRouteImport.update({
  id: '/cliente/visitas',
  path: '/cliente/visitas',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteFavoritosRoute = ClienteFavoritosRouteImport.update({
  id: '/cliente/favoritos',
  path: '/cliente/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUtilizadoresRoute = AdminUtilizadoresRouteImport.update({
  id: '/admin/utilizadores',
  path: '/admin/utilizadores',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminImoveisRoute = AdminImoveisRouteImport.update({
  id: '/admin/imoveis',
  path: '/admin/imoveis',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminImoveisInativosRoute = AdminImoveisInativosRouteImport.update({
  id: '/inativos',
  path: '/inativos',
  getParentRoute: () => AdminImoveisRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/login': typeof LoginRoute
  '/login-cliente': typeof LoginClienteRoute
  '/login-funcionarios': typeof LoginFuncionariosRoute
  '/registo': typeof RegistoRoute
  '/sobre': typeof SobreRoute
  '/admin/imoveis': typeof AdminImoveisRouteWithChildren
  '/admin/utilizadores': typeof AdminUtilizadoresRoute
  '/cliente/favoritos': typeof ClienteFavoritosRoute
  '/cliente/visitas': typeof ClienteVisitasRoute
  '/corretor/imoveis': typeof CorretorImoveisRoute
  '/imoveis/$id': typeof ImoveisIdRoute
  '/admin/': typeof AdminIndexRoute
  '/cliente/': typeof ClienteIndexRoute
  '/corretor/': typeof CorretorIndexRoute
  '/imoveis/': typeof ImoveisIndexRoute
  '/admin/imoveis/inativos': typeof AdminImoveisInativosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/login': typeof LoginRoute
  '/login-cliente': typeof LoginClienteRoute
  '/login-funcionarios': typeof LoginFuncionariosRoute
  '/registo': typeof RegistoRoute
  '/sobre': typeof SobreRoute
  '/admin/imoveis': typeof AdminImoveisRouteWithChildren
  '/admin/utilizadores': typeof AdminUtilizadoresRoute
  '/cliente/favoritos': typeof ClienteFavoritosRoute
  '/cliente/visitas': typeof ClienteVisitasRoute
  '/corretor/imoveis': typeof CorretorImoveisRoute
  '/imoveis/$id': typeof ImoveisIdRoute
  '/admin': typeof AdminIndexRoute
  '/cliente': typeof ClienteIndexRoute
  '/corretor': typeof CorretorIndexRoute
  '/imoveis': typeof ImoveisIndexRoute
  '/admin/imoveis/inativos': typeof AdminImoveisInativosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/login': typeof LoginRoute
  '/login-cliente': typeof LoginClienteRoute
  '/login-funcionarios': typeof LoginFuncionariosRoute
  '/registo': typeof RegistoRoute
  '/sobre': typeof SobreRoute
  '/admin/imoveis': typeof AdminImoveisRouteWithChildren
  '/admin/utilizadores': typeof AdminUtilizadoresRoute
  '/cliente/favoritos': typeof ClienteFavoritosRoute
  '/cliente/visitas': typeof ClienteVisitasRoute
  '/corretor/imoveis': typeof CorretorImoveisRoute
  '/imoveis/$id': typeof ImoveisIdRoute
  '/admin/': typeof AdminIndexRoute
  '/cliente/': typeof ClienteIndexRoute
  '/corretor/': typeof CorretorIndexRoute
  '/imoveis/': typeof ImoveisIndexRoute
  '/admin/imoveis/inativos': typeof AdminImoveisInativosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contacto'
    | '/login'
    | '/login-cliente'
    | '/login-funcionarios'
    | '/registo'
    | '/sobre'
    | '/admin/imoveis'
    | '/admin/utilizadores'
    | '/cliente/favoritos'
    | '/cliente/visitas'
    | '/corretor/imoveis'
    | '/imoveis/$id'
    | '/admin/'
    | '/cliente/'
    | '/corretor/'
    | '/imoveis/'
    | '/admin/imoveis/inativos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacto'
    | '/login'
    | '/login-cliente'
    | '/login-funcionarios'
    | '/registo'
    | '/sobre'
    | '/admin/imoveis'
    | '/admin/utilizadores'
    | '/cliente/favoritos'
    | '/cliente/visitas'
    | '/corretor/imoveis'
    | '/imoveis/$id'
    | '/admin'
    | '/cliente'
    | '/corretor'
    | '/imoveis'
    | '/admin/imoveis/inativos'
  id:
    | '__root__'
    | '/'
    | '/contacto'
    | '/login'
    | '/login-cliente'
    | '/login-funcionarios'
    | '/registo'
    | '/sobre'
    | '/admin/imoveis'
    | '/admin/utilizadores'
    | '/cliente/favoritos'
    | '/cliente/visitas'
    | '/corretor/imoveis'
    | '/imoveis/$id'
    | '/admin/'
    | '/cliente/'
    | '/corretor/'
    | '/imoveis/'
    | '/admin/imoveis/inativos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactoRoute: typeof ContactoRoute
  LoginRoute: typeof LoginRoute
  LoginClienteRoute: typeof LoginClienteRoute
  LoginFuncionariosRoute: typeof LoginFuncionariosRoute
  RegistoRoute: typeof RegistoRoute
  SobreRoute: typeof SobreRoute
  AdminImoveisRoute: typeof AdminImoveisRouteWithChildren
  AdminUtilizadoresRoute: typeof AdminUtilizadoresRoute
  ClienteFavoritosRoute: typeof ClienteFavoritosRoute
  ClienteVisitasRoute: typeof ClienteVisitasRoute
  CorretorImoveisRoute: typeof CorretorImoveisRoute
  ImoveisIdRoute: typeof ImoveisIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ClienteIndexRoute: typeof ClienteIndexRoute
  CorretorIndexRoute: typeof CorretorIndexRoute
  ImoveisIndexRoute: typeof ImoveisIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registo': {
      id: '/registo'
      path: '/registo'
      fullPath: '/registo'
      preLoaderRoute: typeof RegistoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login-funcionarios': {
      id: '/login-funcionarios'
      path: '/login-funcionarios'
      fullPath: '/login-funcionarios'
      preLoaderRoute: typeof LoginFuncionariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login-cliente': {
      id: '/login-cliente'
      path: '/login-cliente'
      fullPath: '/login-cliente'
      preLoaderRoute: typeof LoginClienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imoveis/': {
      id: '/imoveis/'
      path: '/imoveis'
      fullPath: '/imoveis/'
      preLoaderRoute: typeof ImoveisIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corretor/': {
      id: '/corretor/'
      path: '/corretor'
      fullPath: '/corretor/'
      preLoaderRoute: typeof CorretorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente/': {
      id: '/cliente/'
      path: '/cliente'
      fullPath: '/cliente/'
      preLoaderRoute: typeof ClienteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imoveis/$id': {
      id: '/imoveis/$id'
      path: '/imoveis/$id'
      fullPath: '/imoveis/$id'
      preLoaderRoute: typeof ImoveisIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corretor/imoveis': {
      id: '/corretor/imoveis'
      path: '/corretor/imoveis'
      fullPath: '/corretor/imoveis'
      preLoaderRoute: typeof CorretorImoveisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente/visitas': {
      id: '/cliente/visitas'
      path: '/cliente/visitas'
      fullPath: '/cliente/visitas'
      preLoaderRoute: typeof ClienteVisitasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente/favoritos': {
      id: '/cliente/favoritos'
      path: '/cliente/favoritos'
      fullPath: '/cliente/favoritos'
      preLoaderRoute: typeof ClienteFavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/utilizadores': {
      id: '/admin/utilizadores'
      path: '/admin/utilizadores'
      fullPath: '/admin/utilizadores'
      preLoaderRoute: typeof AdminUtilizadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/imoveis': {
      id: '/admin/imoveis'
      path: '/admin/imoveis'
      fullPath: '/admin/imoveis'
      preLoaderRoute: typeof AdminImoveisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/imoveis/inativos': {
      id: '/admin/imoveis/inativos'
      path: '/inativos'
      fullPath: '/admin/imoveis/inativos'
      preLoaderRoute: typeof AdminImoveisInativosRouteImport
      parentRoute: typeof AdminImoveisRoute
    }
  }
}

interface AdminImoveisRouteChildren {
  AdminImoveisInativosRoute: typeof AdminImoveisInativosRoute
}

const AdminImoveisRouteChildren: AdminImoveisRouteChildren = {
  AdminImoveisInativosRoute: AdminImoveisInativosRoute,
}

const AdminImoveisRouteWithChildren = AdminImoveisRoute._addFileChildren(
  AdminImoveisRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactoRoute: ContactoRoute,
  LoginRoute: LoginRoute,
  LoginClienteRoute: LoginClienteRoute,
  LoginFuncionariosRoute: LoginFuncionariosRoute,
  RegistoRoute: RegistoRoute,
  SobreRoute: SobreRoute,
  AdminImoveisRoute: AdminImoveisRouteWithChildren,
  AdminUtilizadoresRoute: AdminUtilizadoresRoute,
  ClienteFavoritosRoute: ClienteFavoritosRoute,
  ClienteVisitasRoute: ClienteVisitasRoute,
  CorretorImoveisRoute: CorretorImoveisRoute,
  ImoveisIdRoute: ImoveisIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  ClienteIndexRoute: ClienteIndexRoute,
  CorretorIndexRoute: CorretorIndexRoute,
  ImoveisIndexRoute: ImoveisIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
